PAD_WORD = '<pad>'
PAD=0
BOS_WORD = '<bos>'
BOS=1
UNK_WORD = '<unk>'
UNK = 2
EOS_WORD = '<eos>'
EOS=3
LINESEP_WORD = '</s>'
LINESEP=4

id2vocab=dict({PAD:PAD_WORD, BOS:BOS_WORD, UNK:UNK_WORD, EOS:EOS_WORD, LINESEP:LINESEP_WORD})
vocab2id=dict({PAD_WORD:PAD, BOS_WORD:BOS, UNK_WORD:UNK, EOS_WORD:EOS, LINESEP_WORD:LINESEP})

